# Generated by Django 5.0.4 on 2025-02-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('unique_name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(default='generateID', max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
