# Generated by Django 5.0.4 on 2025-02-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('upto10k', '10k'), ('abovetill100k', '10kTo100k')], default='upto10k', max_length=100),
        ),
    ]
