# Generated by Django 5.0.4 on 2025-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_alter_member_unique_id_alter_member_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='unique_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
