# Generated by Django 5.0.4 on 2025-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_member_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='unique_id',
            field=models.CharField(max_length=256),
        ),
    ]
