# Generated by Django 5.0.4 on 2025-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_alter_member_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memid', models.CharField(max_length=256)),
                ('memname', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Memtransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memid', models.CharField(max_length=256)),
                ('merkleroot', models.CharField(max_length=256)),
                ('jsonpath', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.CharField(max_length=256)),
                ('fname', models.CharField(max_length=100)),
                ('toidd', models.CharField(max_length=256)),
                ('toname', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Twoconfirms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.CharField(max_length=256)),
                ('toid', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('imanagerstatus', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='intransaction',
            field=models.IntegerField(default=0),
        ),
    ]
