# Generated by Django 5.0.4 on 2025-02-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_cmanager_memtransactions_proposer_twoconfirms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtransactions',
            name='merkleroot',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
